-- MySQL Script generated by MySQL Workbench
-- Thu May  6 14:34:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sms` ;

-- -----------------------------------------------------
-- Schema sms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sms` DEFAULT CHARACTER SET utf8 ;
USE `sms` ;

-- -----------------------------------------------------
-- Table `sms`.`annee_scolaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`annee_scolaire` ;

CREATE TABLE IF NOT EXISTS `sms`.`annee_scolaire` (
  `idannee_scolaire` INT NOT NULL AUTO_INCREMENT,
  `date_debut` DATE NULL,
  `date_fin` DATE NULL,
  `label` VARCHAR(64) NULL,
  PRIMARY KEY (`idannee_scolaire`),
  UNIQUE INDEX `idannee_scolaire_UNIQUE` (`idannee_scolaire` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`annulation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`annulation` ;

CREATE TABLE IF NOT EXISTS `sms`.`annulation` (
  `idannulation` INT NOT NULL AUTO_INCREMENT,
  `raison` VARCHAR(256) NULL DEFAULT NULL,
  `cours` INT NOT NULL,
  PRIMARY KEY (`idannulation`),
  INDEX `fk_annulation_cours1_idx` (`cours` ASC),
  UNIQUE INDEX `idannulation_UNIQUE` (`idannulation` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`articles` ;

CREATE TABLE IF NOT EXISTS `sms`.`articles` (
  `idArticles` INT NOT NULL AUTO_INCREMENT,
  `article_contenu` VARCHAR(4096) NULL,
  `titres` VARCHAR(256) NULL,
  `pdf` VARCHAR(45) NULL,
  `categorie` INT NOT NULL,
  `auteur` INT NOT NULL,
  PRIMARY KEY (`idArticles`),
  INDEX `fk_Articles_personne1_idx` (`auteur` ASC),
  UNIQUE INDEX `idArticles_UNIQUE` (`idArticles` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`articles_categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`articles_categorie` ;

CREATE TABLE IF NOT EXISTS `sms`.`articles_categorie` (
  `Articles_idArticles` INT NOT NULL,
  `categorie_idcategorie` INT NOT NULL,
  PRIMARY KEY (`Articles_idArticles`, `categorie_idcategorie`),
  INDEX `fk_Articles_has_categorie_categorie1_idx` (`categorie_idcategorie` ASC),
  INDEX `fk_Articles_has_categorie_Articles1_idx` (`Articles_idArticles` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`autorise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`autorise` ;

CREATE TABLE IF NOT EXISTS `sms`.`autorise` (
  `disponibilte_iddisponibilte` INT NOT NULL,
  `sport_idsport` INT NOT NULL,
  PRIMARY KEY (`disponibilte_iddisponibilte`, `sport_idsport`),
  INDEX `fk_disponibilte_has_sport_sport1_idx` (`sport_idsport` ASC),
  INDEX `fk_disponibilte_has_sport_disponibilte1_idx` (`disponibilte_iddisponibilte` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`categorie` ;

CREATE TABLE IF NOT EXISTS `sms`.`categorie` (
  `idcategorie` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_cat` VARCHAR(64) NULL,
  PRIMARY KEY (`idcategorie`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`cotisations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`cotisations` ;

CREATE TABLE IF NOT EXISTS `sms`.`cotisations` (
  `idcotisations` INT NOT NULL AUTO_INCREMENT,
  `nom_cotisation` VARCHAR(64) NULL,
  `sport_idsport` INT NULL,
  PRIMARY KEY (`idcotisations`),
  INDEX `fk_cotisations_sport1_idx` (`sport_idsport` ASC),
  UNIQUE INDEX `idcotisations_UNIQUE` (`idcotisations` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`cours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`cours` ;

CREATE TABLE IF NOT EXISTS `sms`.`cours` (
  `idcours` INT NOT NULL AUTO_INCREMENT,
  `nbplace` INT NOT NULL,
  `type_sco_vac` VARCHAR(16) NULL,
  `heure_debut` VARCHAR(45) NULL,
  `duree` INT NULL,
  `date` DATE NULL,
  `cadre` INT NOT NULL,
  `sport` INT NOT NULL,
  PRIMARY KEY (`idcours`),
  INDEX `fk_cours_personne_idx` (`cadre` ASC),
  INDEX `fk_cours_sport1_idx` (`sport` ASC),
  UNIQUE INDEX `idcours_UNIQUE` (`idcours` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`disponibilte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`disponibilte` ;

CREATE TABLE IF NOT EXISTS `sms`.`disponibilte` (
  `iddisponibilte` INT NOT NULL AUTO_INCREMENT,
  `jour_semaine` VARCHAR(16) NULL,
  `heure_debut` DATE NULL,
  `duree` INT NULL,
  `lieu` INT NOT NULL,
  `annee_scolaire` INT NOT NULL,
  PRIMARY KEY (`iddisponibilte`),
  INDEX `fk_disponibilte_lieu1_idx` (`lieu` ASC),
  INDEX `fk_disponibilte_annee_scolaire1_idx` (`annee_scolaire` ASC),
  UNIQUE INDEX `iddisponibilte_UNIQUE` (`iddisponibilte` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`lieu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`lieu` ;

CREATE TABLE IF NOT EXISTS `sms`.`lieu` (
  `idlieu` INT NOT NULL AUTO_INCREMENT,
  `nom_lieu` VARCHAR(64) NULL,
  `adresse` VARCHAR(256) NULL,
  `cp` INT NULL,
  `ville` VARCHAR(32) NULL,
  `lattitude` VARCHAR(16) NULL,
  `longitude` VARCHAR(16) NULL,
  PRIMARY KEY (`idlieu`),
  UNIQUE INDEX `idlieu_UNIQUE` (`idlieu` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`occupation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`occupation` ;

CREATE TABLE IF NOT EXISTS `sms`.`occupation` (
  `semaine` INT NOT NULL,
  `disponibilte` INT NOT NULL,
  `cours_idcours` INT NOT NULL,
  PRIMARY KEY (`semaine`, `disponibilte`, `cours_idcours`),
  INDEX `fk_occupation_disponibilte1_idx` (`disponibilte` ASC),
  INDEX `fk_occupation_cours1_idx` (`cours_idcours` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`participation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`participation` ;

CREATE TABLE IF NOT EXISTS `sms`.`participation` (
  `cours_idcours` INT NOT NULL,
  `personne_idpersonne` INT NOT NULL,
  PRIMARY KEY (`cours_idcours`, `personne_idpersonne`),
  INDEX `fk_cours_has_personne_personne1_idx` (`personne_idpersonne` ASC),
  INDEX `fk_cours_has_personne_cours1_idx` (`cours_idcours` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`personne`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`personne` ;

CREATE TABLE IF NOT EXISTS `sms`.`personne` (
  `idpersonne` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(64) NULL,
  `pwd` VARCHAR(128) NULL,
  `nom` VARCHAR(64) NULL,
  `prenom` VARCHAR(32) NULL,
  `sexe` VARCHAR(8) NULL,
  `birthday` DATE NULL,
  `tel` VARCHAR(16) NULL,
  `adresse` VARCHAR(128) NULL,
  `cp` INT NULL,
  `ville` VARCHAR(32) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `role` INT NOT NULL,
  PRIMARY KEY (`idpersonne`),
  INDEX `fk_personne_role1_idx` (`role` ASC),
  UNIQUE INDEX `idpersonne_UNIQUE` (`idpersonne` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`personne_has_cotisations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`personne_has_cotisations` ;

CREATE TABLE IF NOT EXISTS `sms`.`personne_has_cotisations` (
  `personne_idpersonne` INT NOT NULL,
  `cotisations_idcotisations` INT NOT NULL,
  `annee_scolaire_idannee_scolaire` INT NOT NULL,
  PRIMARY KEY (`personne_idpersonne`, `cotisations_idcotisations`, `annee_scolaire_idannee_scolaire`),
  INDEX `fk_personne_has_cotisations_cotisations1_idx` (`cotisations_idcotisations` ASC),
  INDEX `fk_personne_has_cotisations_personne1_idx` (`personne_idpersonne` ASC),
  INDEX `fk_personne_has_cotisations_annee_scolaire1_idx` (`annee_scolaire_idannee_scolaire` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`poste_elu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`poste_elu` ;

CREATE TABLE IF NOT EXISTS `sms`.`poste_elu` (
  `personne_idpersonne` INT NOT NULL,
  `annee_scolaire_idannee_scolaire` INT NOT NULL,
  `postes_idposte` INT NOT NULL,
  INDEX `fk_poste_personne1_idx` (`personne_idpersonne` ASC),
  INDEX `fk_poste_annee_scolaire1_idx` (`annee_scolaire_idannee_scolaire` ASC),
  INDEX `fk_poste_elu_postes1_idx` (`postes_idposte` ASC),
  PRIMARY KEY (`personne_idpersonne`, `annee_scolaire_idannee_scolaire`, `postes_idposte`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`postes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`postes` ;

CREATE TABLE IF NOT EXISTS `sms`.`postes` (
  `idposte` INT NOT NULL AUTO_INCREMENT,
  `nom_poste` VARCHAR(45) NULL,
  PRIMARY KEY (`idposte`),
  UNIQUE INDEX `idposte_UNIQUE` (`idposte` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`role` ;

CREATE TABLE IF NOT EXISTS `sms`.`role` (
  `idrole` INT NOT NULL AUTO_INCREMENT,
  `nom_role` VARCHAR(16) NULL,
  PRIMARY KEY (`idrole`),
  UNIQUE INDEX `idrole_UNIQUE` (`idrole` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`sport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`sport` ;

CREATE TABLE IF NOT EXISTS `sms`.`sport` (
  `idsport` INT NOT NULL AUTO_INCREMENT,
  `nom_sport` VARCHAR(32) NULL,
  `description` VARCHAR(256) NULL,
  PRIMARY KEY (`idsport`),
  UNIQUE INDEX `idsport_UNIQUE` (`idsport` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`sport_favori`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`sport_favori` ;

CREATE TABLE IF NOT EXISTS `sms`.`sport_favori` (
  `personne_idpersonne` INT NOT NULL,
  `sport_idsport` INT NOT NULL,
  PRIMARY KEY (`personne_idpersonne`, `sport_idsport`),
  INDEX `fk_personne_has_sport_sport1_idx` (`sport_idsport` ASC),
  INDEX `fk_personne_has_sport_personne1_idx` (`personne_idpersonne` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `sms`.`vacances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sms`.`vacances` ;

CREATE TABLE IF NOT EXISTS `sms`.`vacances` (
  `idvacances` INT NOT NULL AUTO_INCREMENT,
  `date_debut` DATE NULL,
  `date_fin` DATE NULL,
  `label` VARCHAR(64) NULL,
  `annee_scolaire` INT NOT NULL,
  PRIMARY KEY (`idvac`),
  INDEX `fk_vacances_annee_scolaire1_idx` (`annee_scolaire` ASC),
  UNIQUE INDEX `idrole_UNIQUE` (`idvac` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sms`.`annee_scolaire`
-- -----------------------------------------------------
START TRANSACTION;
USE `sms`;
INSERT INTO `sms`.`annee_scolaire` (`date_debut`, `date_fin`, `label`) VALUES ('2020-09-01', '2021-08-31', '2020/2021');
INSERT INTO `sms`.`annee_scolaire` (`date_debut`, `date_fin`, `label`) VALUES ('2021-09-01', '2022-08-31', '2021/2022');
INSERT INTO `sms`.`annee_scolaire` (`date_debut`, `date_fin`, `label`) VALUES ('2022-09-01', '2023-08-31', '2022/2023');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sms`.`cotisations`
-- -----------------------------------------------------
START TRANSACTION;
USE `sms`;
INSERT INTO `sms`.`cotisations` (`nom_cotisation`, `sport_idsport`) VALUES ('Cotisation Association', NULL);
INSERT INTO `sms`.`cotisations` (`nom_cotisation`, `sport_idsport`) VALUES ('Cotisation FFTT', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sms`.`cours`
-- -----------------------------------------------------
START TRANSACTION;
USE `sms`;
INSERT INTO `sms`.`cours` (`nbplace`, `type_sco_vac`, `heure_debut`, `duree`, `date`, `cadre`, `sport`) VALUES (10, '1', '18:00:00', 7200, '2021-05-05', 1, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sms`.`disponibilte`
-- -----------------------------------------------------
START TRANSACTION;
USE `sms`;
INSERT INTO `sms`.`disponibilte` (`jour_semaine`, `heure_debut`, `duree`, `lieu`, `annee_scolaire`) VALUES ('mercredi', '16:00:00', 18000, 2, 1);
INSERT INTO `sms`.`disponibilte` (`jour_semaine`, `heure_debut`, `duree`, `lieu`, `annee_scolaire`) VALUES ('mercredi', '16:00:00', 18000, 2, 2);
INSERT INTO `sms`.`disponibilte` (`jour_semaine`, `heure_debut`, `duree`, `lieu`, `annee_scolaire`) VALUES ('mercredi', '19:00:00', 10800, 1, 1);
INSERT INTO `sms`.`disponibilte` (`jour_semaine`, `heure_debut`, `duree`, `lieu`, `annee_scolaire`) VALUES ('mercredi', '19:00:00', 10800, 1, 2);
INSERT INTO `sms`.`disponibilte` (`jour_semaine`, `heure_debut`, `duree`, `lieu`, `annee_scolaire`) VALUES ('jeudi', '18:30:00', 10800, 2, 1);
INSERT INTO `sms`.`disponibilte` (`jour_semaine`, `heure_debut`, `duree`, `lieu`, `annee_scolaire`) VALUES ('jeudi', '18:30:00', 10800, 2, 2);
INSERT INTO `sms`.`disponibilte` (`jour_semaine`, `heure_debut`, `duree`, `lieu`, `annee_scolaire`) VALUES ('vendredi', '18:30:00', 10800, 2, 1);
INSERT INTO `sms`.`disponibilte` (`jour_semaine`, `heure_debut`, `duree`, `lieu`, `annee_scolaire`) VALUES ('vendredi', '18:30:00', 10800, 2, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sms`.`lieu`
-- -----------------------------------------------------
START TRANSACTION;
USE `sms`;
INSERT INTO `sms`.`lieu` (`nom_lieu`, `adresse`, `cp`, `ville`, `lattitude`, `longitude`) VALUES ('Gymnase', '6 rue de l\'abattoir', 21210, 'Saulieu', '47.281566', '4.224807');
INSERT INTO `sms`.`lieu` (`nom_lieu`, `adresse`, `cp`, `ville`, `lattitude`, `longitude`) VALUES ('Marché Couvert', '8 rue Sallier', 21210, 'Saulieu', '47.279744', '4.230499');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sms`.`personne`
-- -----------------------------------------------------
START TRANSACTION;
USE `sms`;
INSERT INTO `sms`.`personne` (`email`, `pwd`, `nom`, `prenom`, `sexe`, `birthday`, `tel`, `adresse`, `cp`, `ville`, `created_at`, `updated_at`, `role`) VALUES ('julien.maignaut@gmail.com', 'b6b15c64dbffa077d4b91f263afbbd7329831d8a74066eb2e01ada57edd210f6a672bf6bae4dab8181db79dee64b63a937c4b82f37df820119676acbf778c24f', 'maignaut', 'julien', 'homme', '1986-09-11', '0665053687', '20 rue de l\'étang', 21210, 'saulieu', NULL, NULL, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sms`.`postes`
-- -----------------------------------------------------
START TRANSACTION;
USE `sms`;
INSERT INTO `sms`.`postes` (`nom_poste`) VALUES ('président');
INSERT INTO `sms`.`postes` (`nom_poste`) VALUES ('président adjoint');
INSERT INTO `sms`.`postes` (`nom_poste`) VALUES ('trésorier');
INSERT INTO `sms`.`postes` (`nom_poste`) VALUES ('trésorier adjoint');
INSERT INTO `sms`.`postes` (`nom_poste`) VALUES ('secrétaire');
INSERT INTO `sms`.`postes` (`nom_poste`) VALUES ('secrétaire adjoint');
INSERT INTO `sms`.`postes` (`nom_poste`) VALUES ('membre du bureau');
INSERT INTO `sms`.`postes` (`nom_poste`) VALUES ('responsable tennis de table');
INSERT INTO `sms`.`postes` (`nom_poste`) VALUES ('reponsable badminton');
INSERT INTO `sms`.`postes` (`nom_poste`) VALUES ('responsable volley');
INSERT INTO `sms`.`postes` (`nom_poste`) VALUES ('bureau tennis de table');
INSERT INTO `sms`.`postes` (`nom_poste`) VALUES ('trésorier tennis de table');
INSERT INTO `sms`.`postes` (`nom_poste`) VALUES ('secrétaire tennis de table');
INSERT INTO `sms`.`postes` (`nom_poste`) VALUES ('président tennis de table');
INSERT INTO `sms`.`postes` (`nom_poste`) VALUES ('comité communication');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sms`.`role`
-- -----------------------------------------------------
START TRANSACTION;
USE `sms`;
INSERT INTO `sms`.`role` (`nom_role`) VALUES ('admin');
INSERT INTO `sms`.`role` (`nom_role`) VALUES ('cadre');
INSERT INTO `sms`.`role` (`nom_role`) VALUES ('user');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sms`.`sport`
-- -----------------------------------------------------
START TRANSACTION;
USE `sms`;
INSERT INTO `sms`.`sport` (`nom_sport`, `description`) VALUES ('badminton', 'sport de raquette, en intérieur');
INSERT INTO `sms`.`sport` (`nom_sport`, `description`) VALUES ('tennis de table', 'sport de raquette en intérieur');
INSERT INTO `sms`.`sport` (`nom_sport`, `description`) VALUES ('volley', 'sport d\'intérieur ou extérieur');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sms`.`vacances`
-- -----------------------------------------------------
START TRANSACTION;
USE `sms`;
INSERT INTO `sms`.`vacances` (`date_debut`, `date_fin`, `label`, `annee_scolaire`) VALUES ('2021-07-06', '2021-09-02', 'vacances d\'été', 1);
INSERT INTO `sms`.`vacances` (`date_debut`, `date_fin`, `label`, `annee_scolaire`) VALUES ('2021-10-23', '2021-11-08', 'vacances de la toussaint', 2);
INSERT INTO `sms`.`vacances` (`date_debut`, `date_fin`, `label`, `annee_scolaire`) VALUES ('2021-12-18', '2022-01-03', 'vacances de noël', 2);
INSERT INTO `sms`.`vacances` (`date_debut`, `date_fin`, `label`, `annee_scolaire`) VALUES ('2022-04-16', '2022-05-03', 'vacances de printemps', 2);
INSERT INTO `sms`.`vacances` (`date_debut`, `date_fin`, `label`, `annee_scolaire`) VALUES ('2022-05-25', '2022-05-30', 'pont de l\'ascension', 2);
INSERT INTO `sms`.`vacances` (`date_debut`, `date_fin`, `label`, `annee_scolaire`) VALUES ('2022-07-07', '2022-08-31', 'vacances d\'été', 2);

COMMIT;

